Add private queue for trusted setup
iron-fish/ironfish pull request #3730
Opened 2023-04-03 22:20 UTC by danield9tqh

## Summary
Since we may not have time for a pre-contribution period, adding a private queue for trusted setup contributions

## Testing Plan
Testing locally running server and client

## Documentation

Does this change require any updates to the Iron Fish Docs (ex. [the RPC API
Reference](https://ironfish.network/docs/onboarding/rpc/chain))? If yes, link a
related documentation pull request for the website.

```
[ ] Yes
```

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
```

2023-04-03 23:04 UTC, dguenther commented on ironfish-cli/src/trusted-setup/server.ts
> +    const nextClient = this.privateQueue.shift() || this.queue.shift()
Neat

2023-04-03 23:12 UTC, dguenther requested changes

2023-04-04 19:48 UTC, danield9tqh commented on ironfish-cli/src/trusted-setup/server.ts
> +        client.send(this.getJoinedMessage(this.totalQueueLength()))
oh right good catch

2023-04-04 19:58 UTC, dguenther approved these changes

2023-04-05 01:28 UTC, merged