adding string length limit to node name
iron-fish/ironfish pull request #4324
Opened 2023-09-29 17:43 UTC by patnir

## Summary

Limiting size of node name to 32 letters. Other peers cannot connect to you if you have a long node name. 

<img width="1381" alt="image" src="https://github.com/iron-fish/ironfish/assets/13268167/fd0716eb-b736-4c63-8447-b8591f80e35e">

## Testing Plan

## Documentation

Does this change require any updates to the Iron Fish Docs (ex. [the RPC API
Reference](https://ironfish.network/docs/onboarding/rpc/chain))? If yes, link a
related documentation pull request for the website.

```
[ ] Yes
```

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
```

2023-09-29 18:53 UTC, jowparks commented
Can you give context as to why other peers can't connect with > 32 char? Wondering what the underlying issue is.

2023-10-12 17:42 UTC, dguenther requested changes
This looks good! One other thing I noticed, I think there's a bug in the PeerManager -- it's supposed to take the first 32 characters when the node name is too long, but it looks like it actually takes characters starting at index 32 (which could still result in more than 32 characters if the string is like 100 chars long). Would you mind adding a fix for that in this PR too?

https://github.com/iron-fish/ironfish/blob/c898a1ee23db85fdfaa549fe21f795832b400591/ironfish/src/network/peerNetwork.ts#L229

2023-10-12 17:43 UTC, dguenther commented
> Can you give context as to why other peers can't connect with > 32 char? Wondering what the underlying issue is.

We have a rule in peerManager that drops connections to peers that identify themselves with a node name greater than 32 chars: https://github.com/iron-fish/ironfish/blob/c898a1ee23db85fdfaa549fe21f795832b400591/ironfish/src/network/peers/peerManager.ts#L1094C8-L1094C8

2023-10-12 18:07 UTC, dguenther approved these changes

2023-10-12 23:09 UTC, merged